[dev]
  command = "pnpm run dev"
  base = "src"
  port = 8888
  targetPort = 5173
  autoLaunch = true
  framework = "vite"

[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/deejai/*"
  to = "https://deej-ai.online/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/setlistfm/*"
  to = "https://api.setlist.fm/rest/1.0/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
