[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/deejai/*"
  to = "https://deej-ai.online/api/v1/:splat"
  status = 200

[[redirects]]
  from = "/api/setlistfm/*"
  to = "https://api.setlist.fm/rest/1.0/:splat"
  status = 200
